// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_CRASHREQ_PAXOS_SGX_CRASH_H_
#define FLATBUFFERS_GENERATED_CRASHREQ_PAXOS_SGX_CRASH_H_

#include "flatbuffers/flatbuffers.h"

#include "crash_generated.h"

namespace paxos_sgx {
namespace crash {

struct SumArgs;
struct SumArgsBuilder;

struct PingArgs;
struct PingArgsBuilder;

struct CloseArgs;
struct CloseArgsBuilder;

struct BasicRequest;
struct BasicRequestBuilder;

enum ReqArgs {
  ReqArgs_NONE = 0,
  ReqArgs_SumArgs = 1,
  ReqArgs_PingArgs = 2,
  ReqArgs_CloseArgs = 3,
  ReqArgs_MIN = ReqArgs_NONE,
  ReqArgs_MAX = ReqArgs_CloseArgs
};

inline const ReqArgs (&EnumValuesReqArgs())[4] {
  static const ReqArgs values[] = {
    ReqArgs_NONE,
    ReqArgs_SumArgs,
    ReqArgs_PingArgs,
    ReqArgs_CloseArgs
  };
  return values;
}

inline const char * const *EnumNamesReqArgs() {
  static const char * const names[5] = {
    "NONE",
    "SumArgs",
    "PingArgs",
    "CloseArgs",
    nullptr
  };
  return names;
}

inline const char *EnumNameReqArgs(ReqArgs e) {
  if (flatbuffers::IsOutRange(e, ReqArgs_NONE, ReqArgs_CloseArgs)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesReqArgs()[index];
}

template<typename T> struct ReqArgsTraits {
  static const ReqArgs enum_value = ReqArgs_NONE;
};

template<> struct ReqArgsTraits<paxos_sgx::crash::SumArgs> {
  static const ReqArgs enum_value = ReqArgs_SumArgs;
};

template<> struct ReqArgsTraits<paxos_sgx::crash::PingArgs> {
  static const ReqArgs enum_value = ReqArgs_PingArgs;
};

template<> struct ReqArgsTraits<paxos_sgx::crash::CloseArgs> {
  static const ReqArgs enum_value = ReqArgs_CloseArgs;
};

bool VerifyReqArgs(flatbuffers::Verifier &verifier, const void *obj, ReqArgs type);
bool VerifyReqArgsVector(flatbuffers::Verifier &verifier, const flatbuffers::Vector<flatbuffers::Offset<void>> *values, const flatbuffers::Vector<uint8_t> *types);

struct SumArgs FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef SumArgsBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VEC = 4
  };
  const flatbuffers::Vector<int64_t> *vec() const {
    return GetPointer<const flatbuffers::Vector<int64_t> *>(VT_VEC);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_VEC) &&
           verifier.VerifyVector(vec()) &&
           verifier.EndTable();
  }
};

struct SumArgsBuilder {
  typedef SumArgs Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_vec(flatbuffers::Offset<flatbuffers::Vector<int64_t>> vec) {
    fbb_.AddOffset(SumArgs::VT_VEC, vec);
  }
  explicit SumArgsBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  SumArgsBuilder &operator=(const SumArgsBuilder &);
  flatbuffers::Offset<SumArgs> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<SumArgs>(end);
    return o;
  }
};

inline flatbuffers::Offset<SumArgs> CreateSumArgs(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::Vector<int64_t>> vec = 0) {
  SumArgsBuilder builder_(_fbb);
  builder_.add_vec(vec);
  return builder_.Finish();
}

inline flatbuffers::Offset<SumArgs> CreateSumArgsDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<int64_t> *vec = nullptr) {
  auto vec__ = vec ? _fbb.CreateVector<int64_t>(*vec) : 0;
  return paxos_sgx::crash::CreateSumArgs(
      _fbb,
      vec__);
}

struct PingArgs FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef PingArgsBuilder Builder;
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           verifier.EndTable();
  }
};

struct PingArgsBuilder {
  typedef PingArgs Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  explicit PingArgsBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  PingArgsBuilder &operator=(const PingArgsBuilder &);
  flatbuffers::Offset<PingArgs> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<PingArgs>(end);
    return o;
  }
};

inline flatbuffers::Offset<PingArgs> CreatePingArgs(
    flatbuffers::FlatBufferBuilder &_fbb) {
  PingArgsBuilder builder_(_fbb);
  return builder_.Finish();
}

struct CloseArgs FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef CloseArgsBuilder Builder;
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           verifier.EndTable();
  }
};

struct CloseArgsBuilder {
  typedef CloseArgs Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  explicit CloseArgsBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  CloseArgsBuilder &operator=(const CloseArgsBuilder &);
  flatbuffers::Offset<CloseArgs> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<CloseArgs>(end);
    return o;
  }
};

inline flatbuffers::Offset<CloseArgs> CreateCloseArgs(
    flatbuffers::FlatBufferBuilder &_fbb) {
  CloseArgsBuilder builder_(_fbb);
  return builder_.Finish();
}

struct BasicRequest FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef BasicRequestBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TYPE = 4,
    VT_TICKET = 6,
    VT_ARGS_TYPE = 8,
    VT_ARGS = 10
  };
  paxos_sgx::crash::ReqType type() const {
    return static_cast<paxos_sgx::crash::ReqType>(GetField<int8_t>(VT_TYPE, 0));
  }
  int64_t ticket() const {
    return GetField<int64_t>(VT_TICKET, 0);
  }
  paxos_sgx::crash::ReqArgs args_type() const {
    return static_cast<paxos_sgx::crash::ReqArgs>(GetField<uint8_t>(VT_ARGS_TYPE, 0));
  }
  const void *args() const {
    return GetPointer<const void *>(VT_ARGS);
  }
  template<typename T> const T *args_as() const;
  const paxos_sgx::crash::SumArgs *args_as_SumArgs() const {
    return args_type() == paxos_sgx::crash::ReqArgs_SumArgs ? static_cast<const paxos_sgx::crash::SumArgs *>(args()) : nullptr;
  }
  const paxos_sgx::crash::PingArgs *args_as_PingArgs() const {
    return args_type() == paxos_sgx::crash::ReqArgs_PingArgs ? static_cast<const paxos_sgx::crash::PingArgs *>(args()) : nullptr;
  }
  const paxos_sgx::crash::CloseArgs *args_as_CloseArgs() const {
    return args_type() == paxos_sgx::crash::ReqArgs_CloseArgs ? static_cast<const paxos_sgx::crash::CloseArgs *>(args()) : nullptr;
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int8_t>(verifier, VT_TYPE) &&
           VerifyField<int64_t>(verifier, VT_TICKET) &&
           VerifyField<uint8_t>(verifier, VT_ARGS_TYPE) &&
           VerifyOffset(verifier, VT_ARGS) &&
           VerifyReqArgs(verifier, args(), args_type()) &&
           verifier.EndTable();
  }
};

template<> inline const paxos_sgx::crash::SumArgs *BasicRequest::args_as<paxos_sgx::crash::SumArgs>() const {
  return args_as_SumArgs();
}

template<> inline const paxos_sgx::crash::PingArgs *BasicRequest::args_as<paxos_sgx::crash::PingArgs>() const {
  return args_as_PingArgs();
}

template<> inline const paxos_sgx::crash::CloseArgs *BasicRequest::args_as<paxos_sgx::crash::CloseArgs>() const {
  return args_as_CloseArgs();
}

struct BasicRequestBuilder {
  typedef BasicRequest Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_type(paxos_sgx::crash::ReqType type) {
    fbb_.AddElement<int8_t>(BasicRequest::VT_TYPE, static_cast<int8_t>(type), 0);
  }
  void add_ticket(int64_t ticket) {
    fbb_.AddElement<int64_t>(BasicRequest::VT_TICKET, ticket, 0);
  }
  void add_args_type(paxos_sgx::crash::ReqArgs args_type) {
    fbb_.AddElement<uint8_t>(BasicRequest::VT_ARGS_TYPE, static_cast<uint8_t>(args_type), 0);
  }
  void add_args(flatbuffers::Offset<void> args) {
    fbb_.AddOffset(BasicRequest::VT_ARGS, args);
  }
  explicit BasicRequestBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  BasicRequestBuilder &operator=(const BasicRequestBuilder &);
  flatbuffers::Offset<BasicRequest> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<BasicRequest>(end);
    return o;
  }
};

inline flatbuffers::Offset<BasicRequest> CreateBasicRequest(
    flatbuffers::FlatBufferBuilder &_fbb,
    paxos_sgx::crash::ReqType type = paxos_sgx::crash::ReqType_sum,
    int64_t ticket = 0,
    paxos_sgx::crash::ReqArgs args_type = paxos_sgx::crash::ReqArgs_NONE,
    flatbuffers::Offset<void> args = 0) {
  BasicRequestBuilder builder_(_fbb);
  builder_.add_ticket(ticket);
  builder_.add_args(args);
  builder_.add_args_type(args_type);
  builder_.add_type(type);
  return builder_.Finish();
}

inline bool VerifyReqArgs(flatbuffers::Verifier &verifier, const void *obj, ReqArgs type) {
  switch (type) {
    case ReqArgs_NONE: {
      return true;
    }
    case ReqArgs_SumArgs: {
      auto ptr = reinterpret_cast<const paxos_sgx::crash::SumArgs *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case ReqArgs_PingArgs: {
      auto ptr = reinterpret_cast<const paxos_sgx::crash::PingArgs *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case ReqArgs_CloseArgs: {
      auto ptr = reinterpret_cast<const paxos_sgx::crash::CloseArgs *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

inline bool VerifyReqArgsVector(flatbuffers::Verifier &verifier, const flatbuffers::Vector<flatbuffers::Offset<void>> *values, const flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyReqArgs(
        verifier,  values->Get(i), types->GetEnum<ReqArgs>(i))) {
      return false;
    }
  }
  return true;
}

inline const paxos_sgx::crash::BasicRequest *GetBasicRequest(const void *buf) {
  return flatbuffers::GetRoot<paxos_sgx::crash::BasicRequest>(buf);
}

inline const paxos_sgx::crash::BasicRequest *GetSizePrefixedBasicRequest(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<paxos_sgx::crash::BasicRequest>(buf);
}

inline bool VerifyBasicRequestBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<paxos_sgx::crash::BasicRequest>(nullptr);
}

inline bool VerifySizePrefixedBasicRequestBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<paxos_sgx::crash::BasicRequest>(nullptr);
}

inline void FinishBasicRequestBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<paxos_sgx::crash::BasicRequest> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedBasicRequestBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<paxos_sgx::crash::BasicRequest> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace crash
}  // namespace paxos_sgx

#endif  // FLATBUFFERS_GENERATED_CRASHREQ_PAXOS_SGX_CRASH_H_
