// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_CRASH_PAXOS_SGX_CRASH_H_
#define FLATBUFFERS_GENERATED_CRASH_PAXOS_SGX_CRASH_H_

#include "flatbuffers/flatbuffers.h"

namespace paxos_sgx {
namespace crash {

enum ReqType {
  ReqType_sum = 0,
  ReqType_ping = 1,
  ReqType_close = 2,
  ReqType_MIN = ReqType_sum,
  ReqType_MAX = ReqType_close
};

inline const ReqType (&EnumValuesReqType())[3] {
  static const ReqType values[] = {
    ReqType_sum,
    ReqType_ping,
    ReqType_close
  };
  return values;
}

inline const char * const *EnumNamesReqType() {
  static const char * const names[4] = {
    "sum",
    "ping",
    "close",
    nullptr
  };
  return names;
}

inline const char *EnumNameReqType(ReqType e) {
  if (flatbuffers::IsOutRange(e, ReqType_sum, ReqType_close)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesReqType()[index];
}

}  // namespace crash
}  // namespace paxos_sgx

#endif  // FLATBUFFERS_GENERATED_CRASH_PAXOS_SGX_CRASH_H_
