// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_CRASH_PAXOS_SGX_CRASH_H_
#define FLATBUFFERS_GENERATED_CRASH_PAXOS_SGX_CRASH_H_

#include "flatbuffers/flatbuffers.h"

namespace paxos_sgx {
namespace crash {

enum ReqType {
  ReqType_ping = 0,
  ReqType_close = 1,
  ReqType_transfer = 2,
  ReqType_client_get = 3,
  ReqType_replica_get = 4,
  ReqType_MIN = ReqType_ping,
  ReqType_MAX = ReqType_replica_get
};

inline const ReqType (&EnumValuesReqType())[5] {
  static const ReqType values[] = {
    ReqType_ping,
    ReqType_close,
    ReqType_transfer,
    ReqType_client_get,
    ReqType_replica_get
  };
  return values;
}

inline const char * const *EnumNamesReqType() {
  static const char * const names[6] = {
    "ping",
    "close",
    "transfer",
    "client_get",
    "replica_get",
    nullptr
  };
  return names;
}

inline const char *EnumNameReqType(ReqType e) {
  if (flatbuffers::IsOutRange(e, ReqType_ping, ReqType_replica_get)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesReqType()[index];
}

}  // namespace crash
}  // namespace paxos_sgx

#endif  // FLATBUFFERS_GENERATED_CRASH_PAXOS_SGX_CRASH_H_
